services:
  react-app:
    build:
      context: .
    volumes:
      - .:/app
      - /app/node_modules # Keep node_modules inside container
    ports:
      - '3000:3000'
    env_file:
      - .env
    networks:
      - keycloak-auth_keycloak_network

networks:
  keycloak-auth_keycloak_network:
    external: true
# #
# version: '3.9'

# services:
#   react-app:
#     build:
#       context: .
#     ports:
#       - '3000:3000'
#     env_file:
#       - .env
#     networks:
#       - keycloak-auth_keycloak_network
# networks:
#   keycloak-auth_keycloak_network:
#     external: true
